/* eslint-disable sonarjs/no-duplicate-string */
import { IBots } from 'types';

export const BOTS: IBots[] = [
  {
    title: 'Crypto Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: [ 'Discord'],
    category: ['Application', 'Information'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Information'],
    license: ['Commercial'],
  },
  {
    title: 'Image Telegram Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Other'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Administration' ],
    license: ['Commercial'],
  },

// ------------------------------------------------

  {
    title: 'Crypto Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: [ 'Discord'],
    category: ['Application', 'Information'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Information'],
    license: ['Commercial'],
  },
  {
    title: 'Image Telegram Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Other'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Administration' ],
    license: ['Commercial'],
  },

  {
    title: 'Crypto Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: [ 'Discord'],
    category: ['Application', 'Information'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Information'],
    license: ['Commercial'],
  },
  {
    title: 'Image Telegram Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Other'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Administration' ],
    license: ['Commercial'],
  },

  {
    title: 'Crypto Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: [ 'Discord'],
    category: ['Application', 'Information'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Information'],
    license: ['Commercial'],
  },
  {
    title: 'Image Telegram Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Other'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Administration' ],
    license: ['Commercial'],
  },

  {
    title: 'Crypto Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: [ 'Discord'],
    category: ['Application', 'Information'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Information'],
    license: ['Commercial'],
  },
  {
    title: 'Image Telegram Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Other'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Administration' ],
    license: ['Commercial'],
  },

  {
    title: 'Crypto Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: [ 'Discord'],
    category: ['Application', 'Information'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Information'],
    license: ['Commercial'],
  },
  {
    title: 'Image Telegram Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Other'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Administration' ],
    license: ['Commercial'],
  },

  {
    title: 'Crypto Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: [ 'Discord'],
    category: ['Application', 'Information'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Information'],
    license: ['Commercial'],
  },
  {
    title: 'Image Telegram Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Support', 'Other'],
    license: ['Free'],
  },

  {
    title: 'Find Influencer Bot',
    body: 'Lorem ipsum description lorem ipsum dolor sit amet etc. Lorem ipsum description lorem ipsum dolor sit amet etc...',
    telegramUrl: 'http://tg.com/',
    discordUrl: 'http://discord.com/',
    monthlyPrice: 15,
    yearlyPrice: 12,
    platform: ['Telegram', 'Discord'],
    category: ['Administration' ],
    license: ['Commercial'],
  }
  
];
